### ISSUE TITLE
Add support for TOML files with -c, --config

### ISSUE THREAD

**Issue by ijacobs-cpa** [Amnish04/til-page-builder#10]
I would like to add support for passing [TOML](https://toml.io/en/) files for configuration options as an alternative to providing different options in the command line. 

Using `-c`, `--config` with an appropriate `.toml` file as an argument will be accepted as input and will replace any of the individual options in your program (lang, output). To parse the TOML file contents, I'll use the [tomli](https://github.com/hukkin/tomli) TOML file parser to get the file contents.

If this solution is okay, let me know. Thanks

**Comment by Amnish04** [comment]
Sure, please go ahead with it @ijacobs-cpa .

**Note:** I just merged a PR with major refactoring to how markdown processing is done. Please pull the latest changes from `master` before starting your work.

**Comment by Amnish04** [comment]
@ijacobs-cpa Also, I think you should mostly only need to make changes to `src/utils/commandline.py` file.
