### ISSUE TITLE
Normalizing New Lines

### ISSUE THREAD

**Issue by Namatuzio** [Amnish04/til-page-builder#2]
Leaving a double new line creates a blank paragraph tag when converted to HTML

![image](https://github.com/Amnish04/til-page-builder/assets/55001591/c2220181-98bc-43dd-82c1-cba462d83ec1)
![image](https://github.com/Amnish04/til-page-builder/assets/55001591/16d0a498-36d0-44de-8be3-b34acd964575)

**Comment by Amnish04** [comment]
Thanks for spotting the issue. Just fixed a push for that
[Fix Commit](https://github.com/Amnish04/til-page-builder/commit/33355ac993c50b8b03e425229b4884e5e9c2b8e2)
