### ISSUE TITLE
Single File Conversion

### ISSUE THREAD

**Issue by Namatuzio** [Amnish04/til-page-builder#3]
It doesn't seem like single-file conversion works, at least on my machine... 

When I try running `py src/til-builder_main.py hello.txt` it throws this traceback.
![image](https://github.com/Amnish04/til-page-builder/assets/55001591/d53c0f8d-1897-4afd-91c6-7ca9ca353894)

I'm not too sure what might cause it but it seems to be here, in `html_builder.py` 
![image](https://github.com/Amnish04/til-page-builder/assets/55001591/6e19648d-692d-4b9e-adb9-6479b881c5dd)

When I try printing file when I pass a single text file it shows me this: 
![image](https://github.com/Amnish04/til-page-builder/assets/55001591/817ebd29-7de7-4748-a4b7-2c4da2108e03)
![image](https://github.com/Amnish04/til-page-builder/assets/55001591/ce9daa9a-82f8-4bdd-b640-0886753b87fb)

Converting an entire folder works though.

This is strange because it appears to understand that it is a file path as shown here in `til-builder_main.py`:
![image](https://github.com/Amnish04/til-page-builder/assets/55001591/65a94217-8c5c-48fe-a0a9-be4105d4169d)

This also reminded me that it appears that `generate_files()` on line 45 in `til-builder_main.py` is missing an argument. Adding `input_path` to the args did not work though.

**Comment by Amnish04** [comment]
Thanks for detecting this issue. I have to say it was a major one.

And yes, your last line in the issue description was the problem. I forgot to pass the `files_to_be_generated` array to the functions in case of a single file.

[Commit for fix](https://github.com/Amnish04/til-page-builder/commit/c3f0886c5552dad5f39ba1c33eb5ae66383b27eb)
