### ISSUE TITLE
Output Option

### ISSUE THREAD

**Issue by Namatuzio** [Amnish04/til-page-builder#5]
It seems like the default ./til value doesn't do anything when using the `-o` option when running the script in the `commandline.py` file. Overall this is very minor though because if someone were to specify output they most likely wouldn't want to use ./til. 

Overall nicely made. It also made me realize there are certain functionalities I have yet to implement in mine.

**Comment by Amnish04** [comment]
Hi @Namatuzio, did you mean like this
```
python  .\src\til-builder_main.py .\examples\test.txt -o ./til
```
I tried the command and this is what I got:
![image](https://github.com/Amnish04/til-page-builder/assets/78865303/16f5e3cd-203e-4c8f-9d12-be0760976959)

which looks fine to me.
Could you please verify if the issue exists or if I misunderstood the problem?
