### ISSUE TITLE
Add Markdown Support

### ISSUE THREAD

**Issue by bryce-seefieldt** [Amnish04/til-page-builder#6]
RE: Lab 2 - I Would like to work on your code to add Markdown functionality.  Will include recognition and formating of Italics, Bold, Heading 1, Heading 2 Markdown elelments.

**Comment by Amnish04** [comment]
Hi @bryce-seefieldt, please feel free to work on the additions.

I would appreciate it if you follow the following preferences:
1. Create a new file `src/builder/markdown_parser.py` that could include a function called `generate_markdown` similar to `generate_html_for_file` in `src/builder/html_builder.py`.
2. Import the function from new file into `src/builder/html_builder.py` and make use of it in the `generate_files` function.
3. Make use of `line_queries` module I built in the `src/builder` directory to detect type of line in an easy and elegant manner. You are free to add more helpers to `line_queries` as you need.

Thanks

**Comment by Amnish04** [comment]
The feature has been implmented. Closing the issue
